#include "AssetRegistry/AssetRegistryModule.h"
#include "AssetRegistry/IAssetRegistry.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"
#include "HAL/FileManager.h"
#include "Interfaces/IPluginManager.h"
#include "Misc/CommandLine.h"
#include "Misc/CoreDelegates.h"
#include "Misc/EngineVersion.h"
#include "Misc/FileHelper.h"
#include "Misc/PackageName.h"
#include "Misc/Parse.h"
#include "Misc/Paths.h"
#include "Modules/ModuleManager.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonWriter.h"
#include "UObject/SoftObjectPtr.h"
#include "UObject/UnrealType.h"

namespace UnrealAssetToolVFX
{
#include "UnrealAssetToolVFXCore.inl"
#include "UnrealAssetToolVFXReflection.inl"
#include "UnrealAssetToolVFXNiagara.inl"
#include "UnrealAssetToolVFXNiagaraStateless.inl"
#include "UnrealAssetToolVFXNiagaraAssets.inl"
#include "UnrealAssetToolVFXCascade.inl"
#include "UnrealAssetToolVFXDriver.inl"
}
